# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/api/vehicles"
  to = "https://us-central1-sixt-hackatum-2021.cloudfunctions.net/api/vehicles"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"